server:
  port: 8001
spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka