server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          url: https://github.com/A-caro/proyects.git
          search-paths: config-data

  application:
    name: config-server


